### ISSUE TITLE
Add Contribution.md

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [sethshivam11/college-management#1]
Hey @sethshivam11 ,
To streamline the contribution process and make it easier for new contributors to get involved, it's important to have clear and detailed contribution guidelines. A CONTRIBUTING.md file outlines the steps and best practices for contributing to the project, ensuring consistency and high-quality contributions.
Please assign me this issue

**Comment by sethshivam11** [comment]
@Santhosh-Siddhardha Are you still on it?

**Comment by Sibam-Paul** [comment]
@sethshivam11 Hey I wanna work on this under gssoc'24 if it is still open please assign me

**Comment by Braj-01** [comment]
Pls assign me this task under GSSOC'24 if it is not assigned to anyone
