### ISSUE TITLE
[Feat]: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [sethshivam11/college-management#11]
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

![Close Old PRs](https://github.com/sethshivam11/campus-space/assets/115717746/ab3e7f43-1208-40c1-a6aa-65a20d0ff70d)

**Comment by Asymtode712** [comment]
@sethshivam11 please assign me this issue

**Comment by Asymtode712** [comment]
@sethshivam11 please assign me this issue

**Comment by gopalepic** [comment]
hey @sethshivam11

**Comment by sethshivam11** [comment]
@gopalepic this is not the landing page issue.

**Comment by gopalepic** [comment]
just a second @sethshivam11
