### ISSUE TITLE
Add a Landing Page to Campus Space

### ISSUE THREAD

**Issue by Asymtode712** [sethshivam11/college-management#12]
The Campus Space application currently lacks a dedicated landing page. A landing page is crucial for providing a welcoming and informative first impression to users, including students, teachers, and administrators. This page should succinctly describe the features and benefits of Campus Space, guiding users to their respective functionalities within the application.

**Comment by Asymtode712** [comment]
@sethshivam11 please assign me this issue

**Comment by sethshivam11** [comment]
Please build a landing page which matches the theming of the website. I have used [Shadcn](https://ui.shadcn.com) in it.

**Comment by sethshivam11** [comment]
@Asymtode712 Please build a landing page which matches the theming of the website. I have used [Shadcn](https://ui.shadcn.com/) in it.

**Comment by Asymtode712** [comment]
@sethshivam11 sure

**Comment by gopalepic** [comment]
hey @sethshivam11

**Comment by gopalepic** [comment]
I soon will be sharing some picture about the landing page @sethshivam11

**Comment by gopalepic** [comment]
Thanyou @sethshivam11  ,let me start working on this ...

**Comment by gopalepic** [comment]
@sethshivam11  as i started with your project , I try to run locally your code 

MONGODB_URI="mongodb://localhost:27017" #"mongodb://127.0.0.1:27017/"
PORT=27017
ACCESS_TOKEN_SECRET="YOUR_SECRET_TOKEN"
NODE_ENV="production" # Expected value "production".

I wanted to know the what should be the value of this ACCESS_TOKEN_SECRET

**Comment by sethshivam11** [comment]
@gopalepic the port number should be different from 27017 because MongoDB server is running on it and the value of ACCCES_TOKEN_SECRET can be any string

**Comment by gopalepic** [comment]
@sethshivam11  yes , i put 3000 there , so means there is not use of Access_token_secret in the application ?? cause I just wanted to know what should be filled there , or I need to get this secret key from somewhere on the internet?

**Comment by sethshivam11** [comment]
@gopalepic Just enter any random string as secret, it is used to create a unique jsonwebtoken

**Comment by gopalepic** [comment]
@sethshivam11 got it bro

**Comment by gopalepic** [comment]
@sethshivam11 
in the landing page , i would like to add some info about the campus space , its will be of 3 to 4 line , can you provide me some context of your website , so that I can use that information to make a decorative landing page

**Comment by sethshivam11** [comment]
@gopalepic It is a platform made for any institution so that they can manage their classrooms efficiently. It provides students and teachers to see which rooms in the college are vacant/empty so that they can take use of it. When a teacher finds an empty room he/she log into their account and book the required room. The data is managed by the admin on a daily basis. Students can also view their timetable and teachers who are absent.

**Comment by sethshivam11** [comment]
@gopalepic are you still working on it?

**Comment by gopalepic** [comment]
> @gopalepic are you still working on it?

@sethshivam11 yesterday I got discharged from hospital 
And yess I am working on it.

**Comment by sethshivam11** [comment]
@gopalepic Sorry and get well soon 🙏.

**Comment by gopalepic** [comment]
@sethshivam11 i started building landing page , i add the context related to your website , is there any thing you wanted to put in the landing page , for example any image , some buttons or etc

**Comment by sethshivam11** [comment]
@gopalepic No, just make it informative and a little bit animated.

**Comment by gopalepic** [comment]
Should we use this image as out landing page main image @sethshivam11 
![image](https://github.com/sethshivam11/campus-space/assets/145182240/ab633c66-59c1-46ae-9992-568b6ec6d6a7)

**Comment by sethshivam11** [comment]
@gopalepic Okk, use it but make sure it matches the overall theming of the site.

**Comment by gopalepic** [comment]
@sethshivam11 sure!

**Comment by gopalepic** [comment]
do you like it ??

![Screenshot 2024-06-07 145437](https://github.com/sethshivam11/campus-space/assets/145182240/7b4381ef-6997-4e25-9f04-1b24559c4174)

**Comment by sethshivam11** [comment]
@gopalepic Are you working on it?

**Comment by sethshivam11** [comment]
@gopalepic Looks like you're not working on this issue. So, I'm closing this issue now.
