### ISSUE TITLE
Filtering rows 

### ISSUE THREAD

**Issue by sahithi-1729** [sethshivam11/college-management#15]
Filter the rows based on the capacity and floor number the user expects. Suppose the student wants empty classes in 3rd floor he can filter the rows by selecting in the dropdown menu I implement.

please assign me this issue

**Comment by sahithi-1729** [comment]
under gssoc'24

**Comment by sethshivam11** [comment]
But I had already sorted it according to the location i.e. ground floor rooms will be on top, then first, then second.
