### ISSUE TITLE
Implement Update Room Details in the backend

### ISSUE THREAD

**Issue by sethshivam11** [sethshivam11/college-management#16]
Create a controller under [room.controller.ts](https://github.com/sethshivam11/campus-space/blob/master/server/src/controllers/room.controller.ts) named updateRoom.

Expected behavior:
It takes roomId, roomNumber, location, capacity in req.body and saves it to the database after checking all the details such as - either one of the fields are provided in the request body, room exists with provided roomId.

**Comment by Parth18Shah** [comment]
@sethshivam11  Please assign me this issue under gssoc'24.

**Comment by Parth18Shah** [comment]
Please assign the necessary labels as well. Thanks!

**Comment by sethshivam11** [comment]
@Parth18Shah Are you still on it?

**Comment by Parth18Shah** [comment]
Yes, i am

**Comment by Arghadip-Chatterjee** [comment]
Hey, @Parth18Shah I am the Mentor of this Project. If You need any Help, Then Comment it Below. Thanks !! Happy Coding !!

**Comment by Parth18Shah** [comment]
Thank you for your message @Arghadip-Chatterjee. Will definitely reach out to you if needed.
