### ISSUE TITLE
Updating the Font style of the entire UI

### ISSUE THREAD

**Issue by Khanishsuresh** [sethshivam11/college-management#17]
By changing the font style in the website, the UI would be attractive and it will be easier for the user to gothrough

**Comment by Khanishsuresh** [comment]
Hii @sethshivam11 ,

i would like to work on this issue 
would u please assign me to this issue under GSSOC'24 with respective levels

**Comment by Khanishsuresh** [comment]
hii @sethshivam11 , could u add some levels to this issue

**Comment by gopalepic** [comment]
@sethshivam11 , can i work on this?

**Comment by sethshivam11** [comment]
@Khanishsuresh Are you still working on this issue?

**Comment by sethshivam11** [comment]
@gopalepic Please wait for any reply from  @Khanishsuresh 
If his reply does not come in 1-2 days, it will be assigned to you.

**Comment by Khanishsuresh** [comment]
@sethshivam11 ,
Since I had some works to do .I was busy
 I will complete this within today

**Comment by sethshivam11** [comment]
@Khanishsuresh Okay

**Comment by gopalepic** [comment]
@sethshivam11  if you have any doubts , you can ask bro

**Comment by gopalepic** [comment]
@sethshivam11  can i know any issue that you wanted to solve first , I will look into the issue

**Comment by sethshivam11** [comment]
@gopalepic It will be good if you see the issue #12 and try to contribute in that.

**Comment by Khanishsuresh** [comment]
@sethshivam11 
Is this font okay?

![image](https://github.com/sethshivam11/campus-space/assets/136162512/36528edb-ce81-42f2-81b6-51fd463528da)


![image](https://github.com/sethshivam11/campus-space/assets/136162512/f28d6058-aff7-4675-ac92-0ae831865ba9)

**Comment by sethshivam11** [comment]
@Khanishsuresh Add some font that looks professional.

**Comment by Khanishsuresh** [comment]
@sethshivam11 ,
ok i will send some response U just check it

**Comment by Khanishsuresh** [comment]
@sethshivam11 ,
in the following fonts, which is nice ... Just check it and let me know i will change 
![image](https://github.com/sethshivam11/campus-space/assets/136162512/441a686e-feda-4985-84b0-9874fe6309ae)

![image](https://github.com/sethshivam11/campus-space/assets/136162512/47dfc4f3-984f-411b-869d-20a240ce8d19)

![image](https://github.com/sethshivam11/campus-space/assets/136162512/42e91a8b-c489-4c12-9e7a-0fad9d56b1e4)

![image](https://github.com/sethshivam11/campus-space/assets/136162512/2fa9a3c7-e98c-4e26-b85f-f9f3e0cc19b9)

![image](https://github.com/sethshivam11/campus-space/assets/136162512/0c9904f1-b219-4801-b97b-5cfa4a501271)

![image](https://github.com/sethshivam11/campus-space/assets/136162512/e6457d7f-3d66-4ba7-8ad4-4ba9c39e6b8d)

**Comment by sethshivam11** [comment]
@Khanishsuresh None of the fonts are looking good, I am closing this issue because the font is looking good as it is.

**Comment by gopalepic** [comment]
> @gopalepic It will be good if you see the issue #12 and try to contribute in that.

Okay @sethshivam11 , I would be better if you assign it to me under GSSOC 24

**Comment by sethshivam11** [comment]
@gopalepic No, I don't want to change the font. Instead, You can contribute by creating a landing page.

**Comment by gopalepic** [comment]
@sethshivam11  I had gone through the issue #11  , wanted to make a landing page that have most of the information of your website 

@sethshivam11 pls assign this #11 issue to me under GSSOC

**Comment by sethshivam11** [comment]
@gopalepic comment on that issue.
