### ISSUE TITLE
Making the header hover part attractive 

### ISSUE THREAD

**Issue by Khanishsuresh** [sethshivam11/college-management#18]
Hii @sethshivam11 ,

i would like to work on this issue 
would u please assign me this issue under GSSOC'24 with respective levels

**Comment by sethshivam11** [comment]
@Khanishsuresh Can you please explain what you want to do?

**Comment by Khanishsuresh** [comment]
@sethshivam11 
By default , a simple hover action is been given 
I would like to make the hover action with some underline animation and more

**Comment by sethshivam11** [comment]
@Khanishsuresh I think underline will be boring, think something else or send SC after implementing underline animation

**Comment by sethshivam11** [comment]
@Khanishsuresh Are still on it?

**Comment by Khanishsuresh** [comment]
@sethshivam11 , Yeah i am on it

**Comment by sethshivam11** [comment]
@Khanishsuresh Okay

**Comment by Khanishsuresh** [comment]
@sethshivam11 
the app is not opening

![image](https://github.com/sethshivam11/campus-space/assets/136162512/f131ca7a-5500-489d-b081-9e794e3a0ae0)

**Comment by sethshivam11** [comment]
@Khanishsuresh You have to provide `NODE_ENV` variable with value `production`

**Comment by Khanishsuresh** [comment]
@sethshivam11 ok i will try

**Comment by Khanishsuresh** [comment]
@sethshivam11 could u add the level for this issue

**Comment by Arghadip-Chatterjee** [comment]
Hey, @Khanishsuresh I am the Mentor of this Project. Have You Added the ENV Variables and is it Working? Do You need any Help ? You Can Comment Below. Thanks !! Happy Coding !!

**Comment by Khanishsuresh** [comment]
@Arghadip-Chatterjee  Yeah its working

**Comment by sethshivam11** [comment]
@Khanishsuresh are you still working on it?

**Comment by sethshivam11** [comment]
@Arghadip-Chatterjee  I am closing this issue because I don't think its a requirement for us.
