### ISSUE TITLE
Missing Learn.md file

### ISSUE THREAD

**Issue by debangi29** [sethshivam11/college-management#19]
Add Learn.md file as instructed by Gssoc guidelines

**Comment by debangi29** [comment]
Please assign me the issue @sethshivam11 under Gssoc'24

**Comment by sethshivam11** [comment]
@debangi29 README.md has everything related to the project.

**Comment by debangi29** [comment]
Okay! Thanks but I guess adding an Learn.md file was made compulsory by the
Gssoc team
No problem,
Thanks and Regards
Debangi Ghosh

**Comment by sethshivam11** [comment]
@debangi29 Are you sure it is compulsory, if yes please send some references.

**Comment by debangi29** [comment]
https://www.youtube.com/live/K55HMy7alag?feature=shared

Please check this guide video for Gssoc, from 10:35
Thank you :)

**Comment by sethshivam11** [comment]
@debangi29 Ok, so start writing the file but you will require details of it. You can ping me on the discord, my username is `sethshivam11`.

**Comment by Arghadip-Chatterjee** [comment]
Hey, @debangi29 I am the Mentor of this Project. I am Assigning You this Issue of Adding learn.md file. If You need any Help, Then Comment it. Thanks !! Happy Coding !! 👍

**Comment by sethshivam11** [comment]
@debangi29 are you still on it?

**Comment by debangi29** [comment]
Yeah yeah I'll complete it by today
I'm really sorry for the delay

**Comment by sethshivam11** [comment]
@debangi29 Okk.

**Comment by sethshivam11** [comment]
@Arghadip-Chatterjee Please review this ![Screenshot_2024-06-06-15-47-22-422_com.github.android.jpg](https://github.com/sethshivam11/campus-space/assets/130232913/3cd1d743-dee4-480b-972f-61baea4ffc74)
