### ISSUE TITLE
Enhancing the navbar and fixing at the top

### ISSUE THREAD

**Issue by Sibam-Paul** [sethshivam11/college-management#23]
### Want to give blur to navbar background with css and fixing at the top

![image](https://github.com/sethshivam11/campus-space/assets/158052549/c6727fa4-047b-46f2-bfcd-f282644e2e15)
- navbar not fixed  
- will change the style of css

_Please assign this issue to be under gssoc'24_

**Comment by Sibam-Paul** [comment]
please give a detail step how to run locally please

**Comment by Sibam-Paul** [comment]
couldn't understand from readme

**Comment by Sibam-Paul** [comment]
@sethshivam11

**Comment by sethshivam11** [comment]
@Sibam-Paul Fork the repo and download it locally, create a .env file in the root folder, with variables:
- MONGODB_URI=YOUR_MONGODB_URI
- PORT=3000
- NODE_ENV=production
- ACCESS_TOKEN_SECRET=ANY_STRING
Then, run `npm run build` in the root folder.
Go to [vite.config.ts](https://github.com/sethshivam11/campus-space/blob/master/client/vite.config.ts) and uncomment the proxy.
Now, run the server using `npm start` in the root folder, open another terminal goto client folder and run `npm run dev`

**Comment by Sibam-Paul** [comment]
@sethshivam11 Showing
![image](https://github.com/sethshivam11/campus-space/assets/158052549/4e963eb6-6fad-4113-bc7b-155265f7aac2)

Please tell

**Comment by Sibam-Paul** [comment]
ok
 @sethshivam11 Please assign me this

**Comment by Sibam-Paul** [comment]
@sethshivam11 please see why giving error
![image](https://github.com/sethshivam11/campus-space/assets/158052549/e265f317-d5b1-4a58-909e-349317f343a1)

**Comment by sethshivam11** [comment]
@Sibam-Paul This is not HTML, Please revise the concepts of React and use tailwind instead of CSS.

**Comment by Sibam-Paul** [comment]
![image](https://github.com/sethshivam11/campus-space/assets/158052549/ccdec367-3026-43aa-81e6-bf0dd1f8ae2e)
made sticky but not updating in the hosting platform
![image](https://github.com/sethshivam11/campus-space/assets/158052549/6a0aa1f6-220f-4a35-ba56-9498c730e366)

Is there any mentor to help
@sethshivam11

**Comment by sethshivam11** [comment]
@Sibam-Paul Can you please check the URL of the localhost, I think you are doing the changes in the file but changes will not reflect in server side hosted frontend. You should see the current changes on [http://localhost:5173](http://localhost:5173)

**Comment by Arghadip-Chatterjee** [comment]
Hey, @Sibam-Paul I am the Mentor of This Project. Can, You Tell me where Your Doubt is ? I think You are Trying to make The Navbar Sticky.

**Comment by Arghadip-Chatterjee** [comment]
@Sibam-Paul You have been Assigned Now

**Comment by Sibam-Paul** [comment]
@Arghadip-Chatterjee yes I have doubt can I pin u in discord

**Comment by Sibam-Paul** [comment]
@Arghadip-Chatterjee can I mail or whatsapp u which i got from ur portfolio

**Comment by Sibam-Paul** [comment]
@Arghadip-Chatterjee yes but I don't know react must just started to learn it .

**Comment by Arghadip-Chatterjee** [comment]
Ok, Whatsapp Me. @Sibam-Paul

**Comment by Arghadip-Chatterjee** [comment]
Ok, @Sibam-Paul I have Merged Your Code and PR. Thanks !! Happy Coding !!
