### ISSUE TITLE
Using mantine table for filter and sorting

### ISSUE THREAD

**Issue by mukilan2815** [sethshivam11/college-management#25]
![image](https://github.com/sethshivam11/campus-space/assets/71129858/700306d2-c409-45c2-affa-8805afde02aa)

In this table we can use mantine table for sorting filtering and pagination for easy access.
Please assign me under GSSOC'24

**Comment by Arghadip-Chatterjee** [comment]
Hey, @mukilan2815 I am the Mentor of this Project. I am Assigning this Feature to You. Thanks !! Happy Coding !!

**Comment by sethshivam11** [comment]
@mukilan2815 I have replied you on the PR.
