### ISSUE TITLE
Bug: Missing sign Up in client side and server side 

### ISSUE THREAD

**Issue by Sibam-Paul** [sethshivam11/college-management#30]
![image](https://github.com/sethshivam11/campus-space/assets/158052549/d8494dec-ba65-483f-ba46-62364e67c792)

Should actually behave:-
The sign up page must be implemented in frontend and must send body to the backend then after sign up sign page should be rendered .. 

_Please assign me this issue under gssoc'24_

**Comment by Sibam-Paul** [comment]
@Arghadip-Chatterjee Please assign me this issue

**Comment by Sibam-Paul** [comment]
@sethshivam11 please assign me this issue

**Comment by sethshivam11** [comment]
@Sibam-Paul It is not implemented because this project is made for a college or school in which only admin and teacher need to sign in. By default, there are two admins created by us further the admin can register any teacher/admin.

**Comment by Sibam-Paul** [comment]
Ok
