### ISSUE TITLE
Bug: Mention steps to open college locally  

### ISSUE THREAD

**Issue by Sibam-Paul** [sethshivam11/college-management#31]
After connecting db and runnning the server the college is showing "College is closed" 

![image](https://github.com/sethshivam11/campus-space/assets/158052549/c61601d2-d339-4679-9f1d-11e2d44b44cb)

It is better to mention steps in documentation to open college locally 

_Please assign me this issue under GSSOC'24_

**Comment by Sibam-Paul** [comment]
@sethshivam11 Please guide me how to make the college open???

**Comment by sethshivam11** [comment]
@Sibam-Paul refer to file [RoomProvider.ts](https://github.com/sethshivam11/campus-space/blob/master/client/src/context/RoomProvider.tsx) and the time is manipulated at line 81. You can hard code it to `8.30-9.30` or something having a format hh-30 and remove the if else blocks.
