### ISSUE TITLE
Enchancing README File

### ISSUE THREAD

**Issue by Ojas-Arora** [sethshivam11/college-management#37]
I will add some more features in README file. Kindly assign this issue to me @sethshivam11

**Comment by Arghadip-Chatterjee** [comment]
Ok, @Ojas-Arora I am Assigning this to You. But I will Suggest You to make Valid Contributions in Codebase without Updating the Readme File. For Now, I am Assigning this to You. Thanks !!

**Comment by sethshivam11** [comment]
@Ojas-Arora Are you still working on it?

**Comment by Ojas-Arora** [comment]
@sethshivam11 The project is not working on local.

**Comment by sethshivam11** [comment]
@Ojas-Arora What errors are you facing?

**Comment by sethshivam11** [comment]
@Ojas-Arora I don't think you need to run the project, as you have to contribute to the README. But, let me know what errors are you facing?

**Comment by Ojas-Arora** [comment]
@sethshivam11 I was actually trying to add some feature in the page and use the commands for it in the README but was not able to run on local but no issue I will just make changes in the README.
