### ISSUE TITLE
Updating the twitter logo

### ISSUE THREAD

**Issue by pani2004** [sethshivam11/college-management#39]
Updating the twitter logo in footer section.
![Screenshot (45)](https://github.com/sethshivam11/campus-space/assets/154724111/485a70bf-4e00-4887-ba91-ac085ef08a06)

**Comment by pani2004** [comment]
@sethshivam11 @Arghadip-Chatterjee  pls assign me this!!

**Comment by Arghadip-Chatterjee** [comment]
Ok, @pani2004 I am Assigning this to You. Thank You !!

**Comment by sethshivam11** [comment]
@pani2004 the issue is still not resolved. The bird icon is still there and not the X.
