### ISSUE TITLE
Add an env-example file

### ISSUE THREAD

**Issue by gunner26735** [sethshivam11/college-management#4]
Creating an env-example file will help the new contributors easily recognize and have an idea about the environment setup variable. 

Can you please assign this issue to me under the GSSOC label?

Thanks

**Comment by sethshivam11** [comment]
@gunner26735 You should check the README file, it contains the environment variables.

**Comment by gunner26735** [comment]
Yes correct but similar to an env-sample which is given in client I thought there should be a sample for server as well.
Because NODE_ENV value and MongoDB sample URI are not mention anywhere that's why I created this issue.

**Comment by sethshivam11** [comment]
Please add a .env.sample file, also update README.md accordingly and also provide a link for the .env.sample file. In the .env.sample file add a comment for NODE_ENV that it's expected value is production.

**Comment by sethshivam11** [comment]
@gunner26735 Please add a .env.sample file, also update README.md accordingly and also provide a link for the .env.sample file. In the .env.sample file add a comment for NODE_ENV that its expected value is production.

**Comment by sethshivam11** [comment]
- In the README.md file write .env.sample in place of .env sample
- Change the name pf file from .env-sample to .env.sample
- Follow the client side [.env.sample](https://github.com/sethshivam11/campus-space/blob/master/client/.env.sample) file for writing the values of variables
- Comment the value of MONGODB_URI given by you after the giving the variable value
- Change the comment for production variable as just "Expected value 'production'"

**Comment by sethshivam11** [comment]
@gunner26735 Please do the following changes
- In the README.md file write .env.sample in place of .env sample
- Change the name pf file from .env-sample to .env.sample
- Follow the client side [.env.sample](https://github.com/sethshivam11/campus-space/blob/master/client/.env.sample) file for writing the values of variables
- Comment the value of MONGODB_URI given by you after the giving the variable value
- Change the comment for production variable as just `Expected value "production"`

**Comment by gunner26735** [comment]
Ok on it.

**Comment by gunner26735** [comment]
@sethshivam11 can you please assign the gssoc label?
