### ISSUE TITLE
Updating and adding a better Contribution.md

### ISSUE THREAD

**Issue by Sibam-Paul** [sethshivam11/college-management#45]
**Is your feature request related to a problem? Please describe.**
Will enhance the contribution.md

![SmartSelect_20240605-093855_Chrome](https://github.com/sethshivam11/campus-space/assets/158052549/fce04bcf-9531-4a32-8d67-d5bffee94173)

**please assign me under GSSOC'24.**

**Comment by Sibam-Paul** [comment]
@sethshivam11 @Arghadip-Chatterjee please assign me this

**Comment by sethshivam11** [comment]
@Sibam-Paul It's suggested that you should make real contributions rather than just updating the markdown files.

**Comment by Sibam-Paul** [comment]
ok
