### ISSUE TITLE
add more social media links and align copyright 

### ISSUE THREAD

**Issue by jayanththalla** [sethshivam11/college-management#49]
**Is your feature request related to a problem? Please describe.**
add more social media links and hover with different colors 

**Describe the solution you'd like**
adding discord,Instagram and alignment of the copy right 

**Additional context**
please assign me @pa
under gssoc and add level

**Comment by sethshivam11** [comment]
@jayanththalla Actually we don't have a Discord or Instagram so, we are not going to add it

**Comment by jayanththalla** [comment]
Alignment of copy right
