### ISSUE TITLE
Add Datesheet Section

### ISSUE THREAD

**Issue by Rags-Mishra** [sethshivam11/college-management#59]
**Is your feature request related to a problem? Please describe.**
Not an issue but kind of an addition to the site.
One feature that can be used here is a date sheet for the nearest examination. 

**Describe the solution you'd like**
I was thinking that instead of keeping it simple as a table with dates and timings, one could utilize calendar by various libraries. One that I saw is [FullCalender](https://fullcalendar.io/)
It will look as such-
- There will be a calendar where the exam dates, holidays will be color coded according to the subject and semester of student (which will be done by logging in).
- Student could click on any of the exam dates and a modal will appear stating details of the exam.

***Kindly assign me this issue under GSSOC'24***

**Comment by sethshivam11** [comment]
@Rags-Mishra yes, I was also thinking of implementing this.

**Comment by sethshivam11** [comment]
@Rags-Mishra can you please do that for the timetable page as well by showing the timetable in the format suggested by you.

**Comment by Rags-Mishra** [comment]
Okay! I will do that. But the time table is on a daily basis, how will it
be represented in a calendar?

**Comment by sethshivam11** [comment]
@Rags-Mishra it's not on a daily basis, it's a weekly basis. I request you to check a timetable.

**Comment by Rags-Mishra** [comment]
@sethshivam11 I am having trouble running the code locally. Can you please help?

**Comment by sethshivam11** [comment]
@Rags-Mishra what errors are you getting?

**Comment by Rags-Mishra** [comment]
Mongodb error
MONGODB_CONNECTION_ERROR !!!! MongooseServerSelectionError: connect
ECONNREFUSED 127.0.0.1:27017

**Comment by sethshivam11** [comment]
@Rags-Mishra Do you have MongoDB installed on your system if not either install it and run the server or create an account on MongoDB atlas and get the connection link and add it in the `.env` file.

**Comment by Rags-Mishra** [comment]
I will try doing this.

**Comment by Rags-Mishra** [comment]
Thank you. It is working now.

**Comment by sethshivam11** [comment]
@Rags-Mishra are you working on it?
