### ISSUE TITLE
[Feat]: Implement Auto Commenting Feat for Issue Creation

### ISSUE THREAD

**Issue by Asymtode712** [sethshivam11/college-management#6]
This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

![issue creation](https://github.com/sethshivam11/campus-space/assets/115717746/a8a446a6-5c43-4dcf-8719-6063fe144be5)

**Comment by Asymtode712** [comment]
@sethshivam11 please assign me this issue

**Comment by sethshivam11** [comment]
@Asymtode712 Please write a good, welcoming message.

**Comment by Asymtode712** [comment]
@sethshivam11 

Welcome to the Campus Space repository! 🎉 We're thrilled to have you here. Thank you for creating this issue! Your initiative is greatly appreciated, and we'll look into it as soon as possible. In the meantime, please make sure to provide all necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly valued and help us improve Campus Space! 😊


Does this message looks good?

**Comment by sethshivam11** [comment]
Great work.

**Comment by sethshivam11** [comment]
@Asymtode712 Great work 👍
