### ISSUE TITLE
Change of Twitter icon at the footer section

### ISSUE THREAD

**Issue by Chandana-756** [sethshivam11/college-management#60]
**Describe the bug**
I have come across that Twitter icon has not being changed at the footer section of the webpage. The Twitter icon should be replaced with "X".

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
![image](https://github.com/sethshivam11/campus-space/assets/94692989/2ceb317e-4aeb-4cbd-9ac9-254673c4c7f0)

**Desktop (please complete the following information):**
 - OS: WindowsOS
 - Browser : Chrome

I would like to work on this issue under GSSOC'24

**Comment by sethshivam11** [comment]
@Chandana-756 I have reopened the issue #39

**Comment by ghost** [comment]
Is there a way I can help here?

**Comment by sethshivam11** [comment]
@shashidharaa You can help in any other issues.
