### ISSUE TITLE
Automatically comment on Pull Request merge

### ISSUE THREAD

**Issue by PradnyaGaitonde** [sethshivam11/college-management#63]
I would like to contribute to the repository by implementing an autocomment feature for merged pull requests. 

This feature will provide a notification to contributors when their pull request is successfully merged, acknowledging their contribution. 

Assigning me this task under gssoc24 would be appreciated, and I am eager to contribute to the project in this capacity.

**Comment by sethshivam11** [comment]
@PradnyaGaitonde Please fix the error in the image
![image](https://github.com/sethshivam11/campus-space/assets/130232913/3b0b15da-1675-41a7-8752-b483bfe3760c)

**Comment by sethshivam11** [comment]
@Arghadip-Chatterjee please review this and unmerge.
