### ISSUE TITLE
Automatically comment on new Pull Requests raised

### ISSUE THREAD

**Issue by PradnyaGaitonde** [sethshivam11/college-management#64]
I am interested in implementing an autocomment feature for newly raised pull requests in the repository. 

This feature will automatically provide contributors with information and guidelines for submitting pull requests, enhancing the contribution process. 

Assigning me this task under gssoc24 would be highly appreciated, and I am excited to contribute to the project in this manner.

**Comment by sethshivam11** [comment]
@PradnyaGaitonde Please look into it. It is not working properly.

**Comment by sethshivam11** [comment]
@Arghadip-Chatterjee please review this and unmerge.
