### ISSUE TITLE
Automatically comment on newly opened issues

### ISSUE THREAD

**Issue by PradnyaGaitonde** [sethshivam11/college-management#65]
I am keen on contributing to the repository by creating an autocomment feature for newly opened issues. 

This feature will promptly acknowledge the creation of issues and provide contributors with relevant information and guidance. I believe implementing this feature would enhance the user experience and streamline the issue management process. 

Assigning me this task under gssoc24 would be a valuable opportunity, and I look forward to contributing to the project in this capacity.

**Comment by sethshivam11** [comment]
@PradnyaGaitonde Please look again into it. Because it is not working properly.

**Comment by sethshivam11** [comment]
@Arghadip-Chatterjee please review and unmerge this.
