### ISSUE TITLE
💡[Feature]: Automatically Comment on Issue Close

### ISSUE THREAD

**Issue by thevijayshankersharma** [sethshivam11/college-management#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am requesting the implementation of a feature that automatically comments on an issue when it is closed in the project repository. This comment will serve as a closing remark, thanking the contributor for their input and providing any necessary follow-up information or next steps.

### Use Case

Implementing this feature would enhance the project's workflow by:

Providing immediate acknowledgment to contributors when their reported issues are resolved.
Standardizing communication and ensuring that contributors are informed about the resolution status of their reported issues.
Improving transparency and reducing ambiguity in the issue resolution process.
This feature would streamline collaboration and contribute to a more efficient and user-friendly experience for all project contributors.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sethshivam11** [comment]
@thevijayshankersharma are you working on it?

**Comment by thevijayshankersharma** [comment]
@sethshivam11 I have already raised PR and got merged to. closing this issue now.

**Comment by sethshivam11** [comment]
@thevijayshankersharma Can you please tell me which PR.

**Comment by thevijayshankersharma** [comment]
https://github.com/sethshivam11/campus-space/pull/67
