### ISSUE TITLE
📝[Docs]:- add tech stack logo on readme file 

### ISSUE THREAD

**Issue by Debayan-Ghosh2005** [sethshivam11/college-management#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

![Screenshot 2024-06-14 213218](https://github.com/sethshivam11/campus-space/assets/149896687/9f86737d-9d6d-4772-afec-95caed0601b7)
 here on the space of writing i want to add logo gor lokking good

### Suggested Change

![Screenshot 2024-06-14 213345](https://github.com/sethshivam11/campus-space/assets/149896687/c6873121-d7b8-4da0-9fd9-b41b29ed4cf3)
u can see this type logo 

### Rationale

i am new at gssoc'24 so small help to making your project add value to my profile

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Debayan-Ghosh2005** [comment]
can you assign me to this . i very new at gssoc,24

**Comment by Debayan-Ghosh2005** [comment]
https://github.com/sethshivam11/campus-space/pull/74#issue-2355834631              i already solve this issues can you do anything for make it correct

**Comment by Debayan-Ghosh2005** [comment]
@sethshivam11 merge the pr plsss

**Comment by sethshivam11** [comment]
@Debayan-Ghosh2005 Okk, but please explain why do you revert that?

**Comment by Debayan-Ghosh2005** [comment]
@Debayan-Ghosh2005  because i forget to mention my issue no for this my pr do not get assign any level so  as you know pr level is very imp for getting score
