### ISSUE TITLE
[Feat]: Auto Commenting feature for PR Raised 

### ISSUE THREAD

**Issue by Asymtode712** [sethshivam11/college-management#7]
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

![PR raised](https://github.com/sethshivam11/campus-space/assets/115717746/80e89402-9a6d-4348-98a2-5a0413f7b1f7)

**Comment by Asymtode712** [comment]
@sethshivam11 please assign me this issue

**Comment by sethshivam11** [comment]
@Asymtode712 Please write good, welcoming message.

**Comment by Asymtode712** [comment]
@sethshivam11 

Welcome to the Campus Space repository! 🎉 Thank you for submitting your pull request! 🙌 We're thrilled to have your contribution and will review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/sujaltangde/JobLane/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Your efforts are highly valued and help us improve Campus Space! 😊

Thanks again for your contribution!

Does this message looks good?

**Comment by sethshivam11** [comment]
@Asymtode712 Yes it's good 👍
