### ISSUE TITLE
Adding more options in timetable section for-stream,course,semester

### ISSUE THREAD

**Issue by AakankshaSarode** [sethshivam11/college-management#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding option in timetable section so resricted for course and other semester for students problem can resolve

### Use Case

adding more option make it more flexsiblity to user who use this website like according to need user can get timetable for there acedemic section.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AakankshaSarode** [comment]
@sethshivam11 please assign this issue to me under GSSOC . I want to work on this issue.

**Comment by sethshivam11** [comment]
@AakankshaSarode I understand your concern, that is happening because we have less number of timetables. And the UI adjusts itself for the provided timetables.
