### ISSUE TITLE
sign up page for new user

### ISSUE THREAD

**Issue by AakankshaSarode** [sethshivam11/college-management#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

creating sign up page for new user who want access the website  after sign up user can login and access the website

### Use Case

adding sign up page new user get added also providing authetication to user  so user can use this website 

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AakankshaSarode** [comment]
@sethshivam11 please assign me this issue under GSSOC. I want to work on this issue.

**Comment by sethshivam11** [comment]
@AakankshaSarode We don't want a signup page because only admins have to add data and teachers can book rooms. If any new teacher came he can get himself registered by contacting the admin.
