### ISSUE TITLE
creating contact page

### ISSUE THREAD

**Issue by AakankshaSarode** [sethshivam11/college-management#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

creating contact page to contact to college any case queries or further details in offline mode.

### Use Case

adding contact page in website so user can directly contact to admin section for any doubt any queries or further details regarding inquires and all.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AakankshaSarode** [comment]
@sethshivam11 I want to work on this issue. please assign me this issue under GSSOC.

**Comment by sethshivam11** [comment]
@AakankshaSarode you are working on it?

**Comment by AakankshaSarode** [comment]
yes I am working on it

**Comment by AakankshaSarode** [comment]
@sethshivam11  acutallly i created contact page in my another folder but when  run frontend without adding feature it not working? can you please  tell me which commond you use to run frontend ? I check in description  there is no commond for frontend and package.json  as well.

**Comment by sethshivam11** [comment]
@AakankshaSarode please let me know what errors are you facing

**Comment by AakankshaSarode** [comment]
Like in ternimal i try to run frontend using commond in json file but that commond not support to run frontend in client side

**Comment by sethshivam11** [comment]
@AakankshaSarode This is because you have not connected your frontend is not connected to a backend. You can fix it by going to vite.config.ts file and add a proxy 
```javascript
server: {
    proxy: {
      "/api/v1": "https://campus-space.onrender.com"
    }
  }
```
But first make sure you visit the site once which will run the server.

**Comment by sethshivam11** [comment]
@AakankshaSarode Are you working on it?

**Comment by AakankshaSarode** [comment]
yes . I was worked on it but I face same issue multiple times . so you can also assigned same issue to other so it help  me also. if they are  able to solve this issue you can assign issue directly.

**Comment by sethshivam11** [comment]
@AakankshaSarode Ok. I understood.
