### ISSUE TITLE
💡[Feature]: Creation of error 404 page.

### ISSUE THREAD

**Issue by taneeshaa15** [sethshivam11/college-management#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

An error 404 page will be created to redirect the users to homepage when the page is no longer available.

### Use Case

I will make an error 404 so that when the user clicks on any broken links or any mistyped url, then the epage will appear.

### Benefits

1.) It will saves time for the user.
2.) It will redirect the user directly to homepage so that the user can get access to other resources.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by taneeshaa15** [comment]
@sethshivam11 Please assign me this issue under gssoc'24.

**Comment by sethshivam11** [comment]
@taneeshaa15 I think you should check again because we have an error page.

**Comment by taneeshaa15** [comment]
@sethshivam11 Can you please provide me with the issue number.

**Comment by sethshivam11** [comment]
@taneeshaa15 This is the [file](https://github.com/sethshivam11/campus-space/blob/master/client/src/components/ErrorPage.tsx)
