### ISSUE TITLE
Feature ✨: Add scroll to top button

### ISSUE THREAD

**Issue by TheNikhilRaj** [sethshivam11/college-management#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @sethshivam11 ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Use Case

@sethshivam11 ,Could you please assign me this issue under gssoc'24 ?

GSSOC'24

### Add ScreenShots

Screenshot(Mandatory):
![343046177-a64505c3-c4e1-432e-bd29-29228d4ab763](https://github.com/sethshivam11/campus-space/assets/129590267/0ed0460f-67dc-48f2-978e-ad3fe8835cb2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sethshivam11** [comment]
@TheNikhilRaj are you working on it?

**Comment by TheNikhilRaj** [comment]
@sethshivam11 Nope!
