### ISSUE TITLE
💡[Feature]: Change the footer 

### ISSUE THREAD

**Issue by jayanththalla** [sethshivam11/college-management#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I have to change the footer where alignment and enhancement is not good

### Use Case

The footer is to be looks proper alignment and all

### Add ScreenShots

![image](https://github.com/sethshivam11/campus-space/assets/121346142/369b5768-b5b7-4350-baba-a1a2a9e662d6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sethshivam11** [comment]
@jayanththalla I think its good, but you can also send your design
