### ISSUE TITLE
🐞[Bug]: Rooms Table

### ISSUE THREAD

**Issue by Sid-80** [sethshivam11/college-management#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The table is inappropriate information about location and capactiy

### Expected behavior

The location attribute should be displayed under location and table. Same goes with capacity...

### Add ScreenShots

![image](https://github.com/sethshivam11/campus-space/assets/101277141/d89915dc-965d-4862-9282-606c46abcba3)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sethshivam11** [comment]
@Sid-80 This just shows the data that you have saved in your DB. I have ensured that the input from the frontend comes in the provided format.
