### ISSUE TITLE
💡[Feature]: Add Stylish Scrollbar

### ISSUE THREAD

**Issue by zalabhavy** [sethshivam11/college-management#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will make scrollbar stylish.

![image](https://github.com/sethshivam11/campus-space/assets/126322584/90b552d7-4b79-4f8b-a921-c0dccfe42f16)

### Use Case

NA

### Benefits

NA

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@sethshivam11 Please assign me this task !

**Comment by sethshivam11** [comment]
@zalabhavy This is a site made for institutions such as College or School. They don't prefer these.
