### ISSUE TITLE
💡[Feature]: Adding a Chatbot

### ISSUE THREAD

**Issue by Ojas-Arora** [sethshivam11/college-management#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@sethshivam11 I want to add Chatbot to the website. Kindly assign me this issue.

### Use Case

Chatbot can help ask any questions about the website.

### Add ScreenShots

![Screenshot 2024-07-12 164605](https://github.com/user-attachments/assets/f710bdd2-8c70-4d80-bdb4-63f1c7d2eb2f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sethshivam11** [comment]
@Ojas-Arora Please explain me how you will be implementing this?

**Comment by Ojas-Arora** [comment]
@sethshivam11 I will implement the chatbot with the help of Tidio App.

**Comment by sethshivam11** [comment]
@Ojas-Arora okk, now you can proceed.
