### ISSUE TITLE
Adding Animated Cursor💡[Feature]: 

### ISSUE THREAD

**Issue by PratikMane0112** [sethshivam11/college-management#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add a animated cursor which will fit to website color scheme & UI.

### Use Case

Enhance to website UX.

### Add ScreenShots

![rgb](https://github.com/user-attachments/assets/d6e4a347-6e91-4466-a571-319ca32e21e4)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sethshivam11** [comment]
@PratikMane0112 Since, this is a site that can be used by an institution, we cannot make it fancy by adding your suggestion.

**Comment by PratikMane0112** [comment]
Ok I can understand, Sorry for my inconvenience.
